# Generated by Django 4.2.7 on 2025-08-02 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("weekly_views", models.PositiveIntegerField(default=0)),
                ("daily_views", models.PositiveIntegerField(default=0)),
                ("total_inquiries", models.PositiveIntegerField(default=0)),
                (
                    "inquiry_conversion_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_favorites", models.PositiveIntegerField(default=0)),
                ("phone_clicks", models.PositiveIntegerField(default=0)),
                ("email_clicks", models.PositiveIntegerField(default=0)),
                ("performance_rank", models.PositiveIntegerField(default=0)),
                (
                    "performance_category",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("average", "Average"),
                            ("poor", "Poor"),
                        ],
                        default="average",
                        max_length=20,
                    ),
                ),
                ("average_time_on_page", models.FloatField(default=0.0)),
                (
                    "bounce_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("top_cities", models.JSONField(default=list)),
                ("mobile_views", models.PositiveIntegerField(default=0)),
                ("desktop_views", models.PositiveIntegerField(default=0)),
                ("tablet_views", models.PositiveIntegerField(default=0)),
                (
                    "price_competitiveness",
                    models.CharField(
                        choices=[
                            ("very_high", "Very High"),
                            ("high", "High"),
                            ("market", "At Market"),
                            ("below_market", "Below Market"),
                            ("bargain", "Bargain"),
                        ],
                        default="market",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Car Analytics",
                "verbose_name_plural": "Car Analytics",
                "db_table": "car_analytics",
            },
        ),
        migrations.CreateModel(
            name="ConversionFunnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("visit", "Website Visit"),
                            ("search", "Search Cars"),
                            ("view", "View Car Details"),
                            ("inquiry", "Send Inquiry"),
                            ("contact", "Contact Seller"),
                            ("test_drive", "Schedule Test Drive"),
                            ("purchase", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("returning_users", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("mobile_users", models.PositiveIntegerField(default=0)),
                ("desktop_users", models.PositiveIntegerField(default=0)),
                ("city_breakdown", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Conversion Funnel",
                "verbose_name_plural": "Conversion Funnel",
                "db_table": "conversion_funnel",
                "ordering": ["-date", "stage"],
            },
        ),
        migrations.CreateModel(
            name="RevenueAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_revenue", models.BigIntegerField(default=0)),
                ("commission_revenue", models.BigIntegerField(default=0)),
                ("featured_listing_revenue", models.BigIntegerField(default=0)),
                ("premium_service_revenue", models.BigIntegerField(default=0)),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                ("average_transaction_value", models.PositiveIntegerField(default=0)),
                (
                    "revenue_growth",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "transaction_growth",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("top_selling_brands", models.JSONField(default=list)),
                ("top_selling_cities", models.JSONField(default=list)),
                ("top_revenue_sellers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Revenue Analytics",
                "verbose_name_plural": "Revenue Analytics",
                "db_table": "revenue_analytics",
                "ordering": ["-start_date", "period_type"],
            },
        ),
        migrations.CreateModel(
            name="SellerAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_listings", models.PositiveIntegerField(default=0)),
                ("active_listings", models.PositiveIntegerField(default=0)),
                ("sold_listings", models.PositiveIntegerField(default=0)),
                ("pending_listings", models.PositiveIntegerField(default=0)),
                ("rejected_listings", models.PositiveIntegerField(default=0)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("total_inquiries", models.PositiveIntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0.0)),
                (
                    "response_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("total_sales_value", models.PositiveIntegerField(default=0)),
                ("average_selling_time", models.PositiveIntegerField(default=0)),
                ("this_month_sales", models.PositiveIntegerField(default=0)),
                (
                    "listing_approval_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "average_quality_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Seller Analytics",
                "verbose_name_plural": "Seller Analytics",
                "db_table": "seller_analytics",
            },
        ),
        migrations.CreateModel(
            name="SystemAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("verified_users", models.PositiveIntegerField(default=0)),
                ("total_listings", models.PositiveIntegerField(default=0)),
                ("new_listings", models.PositiveIntegerField(default=0)),
                ("approved_listings", models.PositiveIntegerField(default=0)),
                ("rejected_listings", models.PositiveIntegerField(default=0)),
                ("sold_listings", models.PositiveIntegerField(default=0)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("total_inquiries", models.PositiveIntegerField(default=0)),
                ("total_searches", models.PositiveIntegerField(default=0)),
                ("total_favorites", models.PositiveIntegerField(default=0)),
                ("total_sales_value", models.BigIntegerField(default=0)),
                ("average_car_price", models.PositiveIntegerField(default=0)),
                (
                    "average_listing_quality",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("average_response_time", models.FloatField(default=0.0)),
                ("top_cities", models.JSONField(default=list)),
                ("city_distribution", models.JSONField(default=dict)),
                (
                    "mobile_traffic_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "desktop_traffic_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "tablet_traffic_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("top_search_terms", models.JSONField(default=list)),
                ("top_brands", models.JSONField(default=list)),
                ("top_price_ranges", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Analytics",
                "verbose_name_plural": "System Analytics",
                "db_table": "system_analytics",
                "ordering": ["-date", "metric_type"],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view_car", "View Car"),
                            ("search", "Search"),
                            ("inquiry", "Send Inquiry"),
                            ("favorite", "Add to Favorites"),
                            ("create_listing", "Create Listing"),
                            ("edit_listing", "Edit Listing"),
                            ("delete_listing", "Delete Listing"),
                            ("upload_image", "Upload Image"),
                            ("calculate_emi", "Calculate EMI"),
                            ("profile_update", "Update Profile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cars.car",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Activity Logs",
                "db_table": "user_activity_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
