# Generated by Django 4.2.7 on 2025-08-02 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
        ("communication", "0001_initial"),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivitylog",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="communication.inquiry",
            ),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="systemanalytics",
            index=models.Index(
                fields=["metric_type", "date"], name="system_anal_metric__290b53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemanalytics",
            index=models.Index(fields=["-date"], name="system_anal_date_302d9f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="systemanalytics", unique_together={("metric_type", "date")},
        ),
        migrations.AddField(
            model_name="selleranalytics",
            name="seller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="revenueanalytics",
            index=models.Index(
                fields=["period_type", "start_date"],
                name="revenue_ana_period__ea3ca2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revenueanalytics",
            index=models.Index(
                fields=["-start_date"], name="revenue_ana_start_d_f76e0c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="revenueanalytics",
            unique_together={("period_type", "start_date", "end_date")},
        ),
        migrations.AddIndex(
            model_name="conversionfunnel",
            index=models.Index(
                fields=["date", "stage"], name="conversion__date_a68e70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversionfunnel",
            index=models.Index(fields=["-date"], name="conversion__date_2c5c25_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="conversionfunnel", unique_together={("stage", "date")},
        ),
        migrations.AddField(
            model_name="caranalytics",
            name="car",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="cars.car",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="user_activi_user_id_543519_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="user_activi_action__1fe201_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["-created_at"], name="user_activi_created_66afa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="selleranalytics",
            index=models.Index(
                fields=["average_rating"], name="seller_anal_average_096421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="selleranalytics",
            index=models.Index(
                fields=["total_sales_value"], name="seller_anal_total_s_eb2e05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="selleranalytics",
            index=models.Index(
                fields=["response_rate"], name="seller_anal_respons_d048ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caranalytics",
            index=models.Index(
                fields=["performance_rank"], name="car_analyti_perform_417241_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caranalytics",
            index=models.Index(
                fields=["total_views"], name="car_analyti_total_v_528843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caranalytics",
            index=models.Index(
                fields=["inquiry_conversion_rate"],
                name="car_analyti_inquiry_a59e05_idx",
            ),
        ),
    ]
