# Generated by Django 4.2.7 on 2025-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_make_car_optional_in_carimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("urgent", "Urgent"),
                    ("very_urgent", "Very Urgent"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
