# Generated by Django 4.2.7 on 2025-08-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("admin_panel", "0001_initial"),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemalert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="systemalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="moderationqueue",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_items",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="moderationqueue",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cars.car",
            ),
        ),
    ]
