# Generated by Django 4.2.7 on 2025-08-02 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("communication", "0001_initial"),
        ("admin_panel", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationqueue",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="communication.inquiry",
            ),
        ),
        migrations.AddField(
            model_name="moderationqueue",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moderationqueue",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_items",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="moderationqueue",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carreview",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_reviews",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="carreview",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_reviews",
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="bulkaction",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_actions",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="adminactivity",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="authentication.adminuser",
            ),
        ),
        migrations.AddField(
            model_name="adminactivity",
            name="affected_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="adminactivity",
            name="affected_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="system_aler_severit_8765c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["alert_type", "is_resolved"],
                name="system_aler_alert_t_6e65ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["is_acknowledged", "is_resolved"],
                name="system_aler_is_ackn_056473_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["-created_at"], name="system_aler_created_f791d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationqueue",
            index=models.Index(
                fields=["status", "priority"], name="moderation__status_634c5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationqueue",
            index=models.Index(
                fields=["assigned_to", "status"], name="moderation__assigne_20d8e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationqueue",
            index=models.Index(
                fields=["item_type", "status"], name="moderation__item_ty_bb0baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moderationqueue",
            index=models.Index(
                fields=["-created_at"], name="moderation__created_efce18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(
                fields=["car", "-created_at"], name="car_reviews_car_id_5216a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(
                fields=["admin", "-created_at"], name="car_reviews_admin_i_6b7473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(fields=["action"], name="car_reviews_action_80b304_idx"),
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(
                fields=["priority"], name="car_reviews_priorit_272587_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkaction",
            index=models.Index(
                fields=["admin", "-created_at"], name="bulk_action_admin_i_108ac8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkaction",
            index=models.Index(fields=["status"], name="bulk_action_status_ad1ffa_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkaction",
            index=models.Index(
                fields=["action_type"], name="bulk_action_action__9d16e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkaction",
            index=models.Index(
                fields=["-created_at"], name="bulk_action_created_f0a72a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminactivity",
            index=models.Index(
                fields=["admin", "-created_at"], name="admin_activ_admin_i_d3c449_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminactivity",
            index=models.Index(
                fields=["activity_type", "-created_at"],
                name="admin_activ_activit_b61c82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adminactivity",
            index=models.Index(
                fields=["-created_at"], name="admin_activ_created_d945cc_idx"
            ),
        ),
    ]
