name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          export GITHUB_PAGES=true
          # Derive base path automatically if not provided via repo Variables
          if [ -z "${{ vars.VITE_PUBLIC_BASE }}" ]; then
            export VITE_PUBLIC_BASE="/${{ github.event.repository.name }}/"
            echo "VITE_PUBLIC_BASE not set; defaulting to $VITE_PUBLIC_BASE"
          else
            export VITE_PUBLIC_BASE="${{ vars.VITE_PUBLIC_BASE }}"
          fi

          if [ -z "${{ vars.VITE_API_URL }}" ]; then
            echo "Warning: VITE_API_URL is not set. Frontend will fallback to protocol//localhost:8000/api/v1"
          else
            export VITE_API_URL="${{ vars.VITE_API_URL }}"
          fi

          npm run build
          # SPA fallback for Pages
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


